# Generated by Django 2.2 on 2019-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0003_auto_20190508_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('lastname', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('profile_image', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
