# Generated by Django 2.2 on 2019-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0005_profile_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_update',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='profile_image',
            field=models.ImageField(default=None, max_length=500, upload_to=''),
        ),
    ]
