# Generated by Django 2.2 on 2019-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0006_auto_20190509_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_update',
            name='profile_image',
            field=models.ImageField(default='default.jpg', max_length=500, upload_to=''),
        ),
    ]
