# Generated by Django 2.2 on 2019-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0008_profile_update_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_update',
            name='desciption',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
