# Generated by Django 2.2 on 2019-05-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0009_auto_20190509_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_update',
            old_name='desciption',
            new_name='description',
        ),
    ]
