# Generated by Django 2.2 on 2019-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0010_auto_20190509_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_update',
            name='city',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='country',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='description',
            field=models.TextField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='lastname',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
