# Generated by Django 2.2 on 2019-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0011_auto_20190509_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_update',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='description',
            field=models.CharField(default='Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='lastname',
            field=models.CharField(default='Lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_update',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
