# Generated by Django 2.2 on 2019-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0014_auto_20190509_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
