# Generated by Django 2.2 on 2019-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkbot', '0015_auto_20190509_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
